### ISSUE TITLE
Basic Vocabulary (US-1)

### ISSUE THREAD

**Issue by ufelgen** [ufelgen/capstone-project#1]
## Value Proposition

**As a** user

**I need** to see a collection of flash cards with word pairs in English as well as
Slovenian (as a representative of the first query language),

**to be able to** review and practice them.

## Description

![image](https://user-images.githubusercontent.com/115288914/206714714-267f37f9-b607-4c21-bc5e-575f5578ede2.png)

## Acceptance Criteria

- [x] Cards with word pairs are rendered in a flexible design (grid 2 equal columns)
- [x] a header is visible displaying the vocab category name
- [x] window content is scrollable (vertically)
- [x] margin is the same for every card
- [x] card size according to text content (height auto)

## Tasks

- [x] branch
- [x] write basic vocab data in dummy array
- [x] render basic vocab as cards using components
- [ ] storybook
- [ ] testing
