### ISSUE TITLE
Add popup menu to delete words (US-6)

### ISSUE THREAD

**Issue by ufelgen** [ufelgen/capstone-project#11]
## Value Proposition

**As a** user
**I want to** be able to delete single words
**so that** I can avoid unnecessary vocabulary in my app.
​

## Description

![image](https://user-images.githubusercontent.com/115288914/208157714-461d8d6c-34a8-4f38-a264-965016765adb.png)

## Acceptance Criteria

- [ ] a ... menu button is added to each word card 
- [ ] clicking this button opens a box element with two options: delete (deletes the card) and close (closes the menu)
- [ ] clicking delete removes the card
- [ ] clicking close closes the menu
- [ ] if all words of a category are deleted, the category vanishes from the overview page
      ​

## Tasks

- [ ] word on branch
- [ ] add a popup box element component with position relative to the card container (its parent element) 
- [ ] include delete and close logic for this popup box as described above

**Comment by flipkoehler** [comment]
very nice story :) 
do you mean "work on branch"?

**Comment by ufelgen** [comment]
> very nice story :) do you mean "work on branch"?

aaah yes 🙈 hopefully there will be more than one word on the branch 😂
thanks!!
