### ISSUE TITLE
Expand popup menu with an edit option (US-7)

### ISSUE THREAD

**Issue by ufelgen** [ufelgen/capstone-project#12]
## Value Proposition

**As a** user
**I want to** edit my vocabulary cards
**so that** I can change things if I made a mistake
​

## Description

![image](https://user-images.githubusercontent.com/115288914/208164523-9cc3c933-041e-40ec-a7c3-12f1047306f3.png)
​

## Acceptance Criteria

- [x] an edit option is added to the popup menu 
- [x] clicking this edit option will turn the card into a form as displayed in the scribble: 
- [x] all fields have their previously specified value as default
- [x] vocab will turn into text input fields
- [x] query language flag and gender field will turn into a dropdown menu
- [x] gender dropdown will appear even if gender wasn't specified previously
- [x] input/choose category field will appear to update category
- [x] exit button to leave edit mode
- [x] update button to save changes
      ​

## Tasks

- [x] work on branch
- [x] add edit option to popup menu component
- [x] upon edit option click, conditionally render form elements to update content as described above
- [x] edit logic will update the word on save (clicking update button)
      ​

**Comment by flipkoehler** [comment]
lgtm :)
