### ISSUE TITLE
add a form for noun declensions (US-8)

### ISSUE THREAD

**Issue by ufelgen** [ufelgen/capstone-project#13]
## Value Proposition

**As a** user
**I want to** have the option to add declensions to nouns and adjectives
**so that** I can better study grammar. 
​

## Description

![image](https://user-images.githubusercontent.com/115288914/208246824-f39e4043-8c17-4af7-81ce-89737ba16ce2.png)

## Acceptance Criteria

- [x] popup ... menu has an "add declension" option
- [x] selecting this option routes to a new form page (see above) 
- [x] submitting the form saves the data and displays the completed declension table 
- [x] the navigation bar has a "back" option which takes the user back to the category overview page (clicking back before submitting loses the data)
- [x] upon submitting the declension form, the popup menu option "add declension" is changed to "see declension"
- [x] selecting this option routes to the declension page (see above) 
      ​

## Tasks

- [x] work on branch
- [x] expand popup menu with "add declension" option
- [x] create declension form component and route (/declension = form, /declension/[slug] = dynamic page for each declension added
- [x] submitting form stores the new data in the overall words array 
- [x] conditionally render navigation element depending on the route

**Comment by Elgin-Schultz** [comment]
Sounds very convincing to me. Just one question pops up in my mind: When submitting the declension form you should be on the new form page? Do you stay on that page when adding? And "see declension" is changed in the background? Or do you get back to the page before and you see "see declension" directly?
