### ISSUE TITLE
case info field (US-9)

### ISSUE THREAD

**Issue by ufelgen** [ufelgen/capstone-project#14]
## Value Proposition

**As a** user
**I want to** see an info field about cases in the declension input form
**so that** I don't get confused about cases. 
​

## Description

![image](https://user-images.githubusercontent.com/115288914/208363718-99715268-efc4-4858-b258-99a090f45555.png)

## Acceptance Criteria

- [x] footer gets another "information" element
- [x] clicking this element opens a popup box with info (in Slovenian) about cases and their respective questions
- [x] clicking the "information" element again closes the info box
      ​

## Tasks

- [x] expand footer by another element
- [x] create popup component as described above

**Comment by Elgin-Schultz** [comment]
Makes sense to me! (Personally just wondering why the language in the info box is German, as the vocabulary pairing seems to be English / Slovenian)...

**Comment by ufelgen** [comment]
> Makes sense to me! (Personally just wondering why the language in the info box is German, as the vocabulary pairing seems to be English / Slovenian)...

Excellent point Elgin, thank you for reviewing my user stories! I put it in German first because in English it's mainly just "who" 🙈 but you're right, it doesn't make a lot of sense, so I removed the German, as I (should) know the questions anyway ;)
