### ISSUE TITLE
edit categories (US-10)

### ISSUE THREAD

**Issue by ufelgen** [ufelgen/capstone-project#17]
## Value Proposition

**As a** user
**I want to** have the option to edit my vocab categories
**so that** I can update or delete them as needed. 
​

## Description

![image](https://user-images.githubusercontent.com/115288914/209357415-05bd19dc-268a-485e-bf63-6a39af38cc80.png)
​

## Acceptance Criteria

- [x] category boxes on category overview page are equipped with a ... button
- [x] clicking the ... button opens a popup menu with the following options:
- [x] "delete" deletes all words in this category (the user has to confirm this through e.g. an alert)
- [x] "edit" reveals an input field with the default value = current category name
- [x] clicking "ok" saves/updates the category name
- [x] "close" closes the popup menu
      ​

## Tasks

- [x] work on branch
- [x] add a popup box element component with position relative to its parent element
- [x]  include delete and close logic for this popup box as described above
- [x]  upon edit option click, conditionally render form element to update category name as described above
- [x]  edit logic will update the category on save (clicking ok button)
- [ ] testing
      ​

**Comment by marvinRoellecke** [comment]
Well done!

Seems like you're not tired of array methods yet 😄

Will the delete button also remove the category or only its entries?

**Comment by ufelgen** [comment]
> Well done!
> 
> Seems like you're not tired of array methods yet 😄
> 
> Will the delete button also remove the category or only its entries?

thanks! :)

hahaha nooope -arrays rock! it will delete the category entirely, because everything is saved in one giant array ;)
