### ISSUE TITLE
add notes (US-11)

### ISSUE THREAD

**Issue by ufelgen** [ufelgen/capstone-project#18]
## Value Proposition

**As a** user
**I want to** add notes to a word 
**so that** I can remember subtleties about the use of different words
​

## Description

![image](https://user-images.githubusercontent.com/115288914/209369012-a23b5e98-bffb-4565-9178-2e805644e1e9.png)

## Acceptance Criteria

- [x] popup ... menu has an "add notes" option
- [x] selecting this option routes to a new form page (see above)
- [x] submitting the form saves the data and displays the notes
- [x] the navigation bar has a "back" option which takes the user back to the category overview page (clicking back before submitting loses the data)
- [x] upon submitting the notes, the popup menu option "add notes" is changed to "see notes"
- [x] selecting this option routes to the notes page (see above)
- [x] notes page has an edit option, where you can update/expand the notes
      ​

## Tasks

- [x] work on branch
- [x] expand popup menu with "add notes" option
- [x] create notes form component and route (/notes = form, /notes/[slug] = dynamic page for each note added
- [x] submitting form stores the notes in the overall words array
- [x] conditionally render navigation element depending on the route
      ​
