### ISSUE TITLE
edit declension form (US-12)

### ISSUE THREAD

**Issue by ufelgen** [ufelgen/capstone-project#19]
## Value Proposition

**As a** user
**I want to** be able to update my declensions  
**so that** I can fix mistakes that I might have made.
​

## Description

![image](https://user-images.githubusercontent.com/115288914/209371964-8f4fb996-6751-4f1f-a83c-9817791af41f.png)

## Acceptance Criteria

- [x] declension form page gets an edit button 
- [x] clicking this button turns the page back into a form with default values = current values
- [x] back button closes edit mode without saving
- [x] save button updates the declension table
      ​

## Tasks

- [x] work on branch
- [x] conditionally render form after button click
- [x] update words array upon save
