### ISSUE TITLE
Display the language and a noun's gender (US-2)

### ISSUE THREAD

**Issue by ufelgen** [ufelgen/capstone-project#2]
## Value Proposition

**As a** user

**I need** to see which language each word is from 
**and I need to** see the query noun's gender displayed

**to be able to** improve my learning experience

## Description

![image](https://user-images.githubusercontent.com/115288914/207011051-0783a4a7-02de-4b7a-ade4-b9f9b9d17149.png)

## Acceptance Criteria

- [x] country flags are displayed in front of every word, reflecting the words's language
- [x] m, f, or n is displayed next to each noun of the query language

## Tasks

- [x] work on a branch
- [x] create a new element next to the query language nouns for gender
- [x] create a new element in front of each word for language/flag
- [x] this element accesses an additional property of the dummy data array, where the gender is stored
- [ ] storybook/ testing

**Comment by flipkoehler** [comment]
can confirm. Looks very good :)
