### ISSUE TITLE
add conjugation for verbs (US-13)

### ISSUE THREAD

**Issue by ufelgen** [ufelgen/capstone-project#23]
## Value Proposition

**As a** user
**I want to** be able to save verb conjugations  
**so that** I can better learn Slovenian 
​

## Description

![image](https://user-images.githubusercontent.com/115288914/209973467-fb329d3a-631f-423f-aab5-ce3e62681dfe.png)
​

## Acceptance Criteria

- [x] vocab card popup menu gets a "+ conjugation" option 
- [x] choosing this option routes to a dynamic /conjugation/[id] page that displays a form (see above)
- [x] after providing 3. person singular present as well as masc. and fem. participles, conjugations for present, past, and future tenses, all conjugations are displayed (see above)
- [x] footer has a back button that routes back to the category
- [x] upon saving conjugation info, a little icon is displayed in the respective vocab card, and the popup menu option changes from "+ conjugation" to "conjugation" 

​

## Tasks

- [x]  work on branch
- [x] expand popup menu with "add conjugation" option
- [x] create conjugation form component and route 
- [x] write a function to correctly conjugate verbs using the information given in the form
- [x] submitting form stores the new data in the overall words array
- [x] conditionally render navigation element depending on the route
