### ISSUE TITLE
edit verb conjugations (US-14)

### ISSUE THREAD

**Issue by ufelgen** [ufelgen/capstone-project#24]
## Value Proposition

**As a** user  
**I want to** have the option to edit the verb conjugation tables 
**in case** the automatically generated conjugations are incorrect for some irregular verbs 
​

## Description

![image](https://user-images.githubusercontent.com/115288914/209974758-f270d34c-b608-4dfa-a86d-59696fa19868.png)

## Acceptance Criteria

- [x] conjugation table pages get an edit button
- [x] clicking this button turns the page into a form with default values = current values
- [x] back button closes edit mode without saving
- [x] save button updates the conjugation table
      ​

## Tasks

- [x] work on branch
- [x] add edit button to conjugation pages
- [x] conditionally render form after button click
- [x] update words array upon save​

**Comment by mihaimazareanu** [comment]
I would add in `Tasks`:

 [ ] add `Edit` button
 
 But that's just me, writing every single detail in the US. 🙈
