### ISSUE TITLE
styling and a11y (US-15)

### ISSUE THREAD

**Issue by ufelgen** [ufelgen/capstone-project#28]
## Value Proposition

**As a** user 
**I want** an accessible and aesthetically pleasing app
**so that** it convinces me to use it. 
​

## Description

n/a
​

## Acceptance Criteria

- [x] no overlap of elements
- [x] color contrast meets a11y criteria
- [x] buttons are styled the same 
- [x] buttons have aria labels
      ​

## Tasks

- [x] refactor some reused styling, e.g. create StyledButton export 
- [x] make the colour a root variable, so that can be more easily adjusted
- [x] optional: add a border radius to the boxes
- [x] add aria labels to all buttons

**Comment by marvinRoellecke** [comment]
> app looks better 

hmmm...etwas subjektiv findest du nicht? Meiner Meinung nach kein gutes Akzeptanzkriterium, da es nicht messbar ist.
Du könntest z.B. einzelne Details festlegen:
- no overlap of elements
- color contrast meets a11y criteria
- ...

**Comment by ufelgen** [comment]
> > app looks better
> 
> hmmm...etwas subjektiv findest du nicht? Meiner Meinung nach kein gutes Akzeptanzkriterium, da es nicht messbar ist. Du könntest z.B. einzelne Details festlegen:
> 
> * no overlap of elements
> * color contrast meets a11y criteria
> * ...

ja guter Punkt, hast Recht. danke!
