### ISSUE TITLE
testing (US-16)

### ISSUE THREAD

**Issue by ufelgen** [ufelgen/capstone-project#29]
## Value Proposition

**As a** developer  
**I want to** add some automated tests to the app
**so that** functions and (reused) components continue to work as intended. 
​

## Description

n/a
​

## Acceptance Criteria

- [x] testing files are added for existing components and functions
- [x] all tests are green (pass)
      ​

## Tasks

- [x] use testing library
- [x] write component tests for existing components (react-testing-library)
- [x] write unit tests for existing functions (jest)
      ​

**Comment by ufelgen** [comment]
> als Beschreibung würde ich hinzufügen welches Testverfahren du nutzt (jest, component testing, ...)
> 
> Möchtest du die Tests nur schreiben, um sie später auf neu geschriebene Funktionen/Komponenten anzuwenden oder testest du auch bereits vorhandenes. In dem Fall würde ich noch reinschreiben, dass du die Tests durchführst und das alle "grün" sind als Akzeptanzkriterium

auch das sind sehr gute Anmerkungen. danke, Marvin!
