### ISSUE TITLE
add categories (US-3)

### ISSUE THREAD

**Issue by ufelgen** [ufelgen/capstone-project#3]
## Value Proposition

**As a** user

**I want to** structure my vocab in different categories

**to be able to** keep track of my vocabulary and learn more efficiently

## Description

![image](https://user-images.githubusercontent.com/115288914/207014031-e25775af-f9a2-4c83-9c96-b242929d0aa3.png)

## Acceptance Criteria

- [x] a page is added which displays a category overview (with the category name and the number of words in this category) 
- [x] when clicked, each category button leads to the vocab list stored under this category name
- [x] the category page has a navigation element at the bottom, which contains a home button leading back to the category overview page
- [x] the category page has a header element at the top, in which the app's name will be displayed (for the (current) lack of a good name, nothing will be written here for now but the header element is distinguishable through a background colour)

## Tasks

- [x] work on a branch 
- [x] routing: category overview page, dynamic [category] page 
- [x] on the category overview page, display number of words in each category
- [x] create navigation element 
- [x] create header element
- [x] access additional arrays in the dummy data for different categories
- [ ] storybook/testing
