### ISSUE TITLE
second language (US-17)

### ISSUE THREAD

**Issue by ufelgen** [ufelgen/capstone-project#30]
## Value Proposition

**As a** user  
**I want to** be able to add a second language translation to my vocab cards  
**so that** I can distinguish words in different languages
​

## Description

![image](https://user-images.githubusercontent.com/115288914/210336400-732a3df7-7bee-44f3-a7ff-c665aaaace33.png)
​

## Acceptance Criteria

- [x] popup ... menu has an "add translation" option
- [x] selecting this option opens a form within the vocab card (see above)
- [x] submitting the form saves the data and displays the new translation
- [x] clicking the back/exit button closes the form without saving the data
- [x] clicking the edit option of the vocab card lets the user edit the whole card including the new translation
      ​

## Tasks

- [x] work on branch
- [x] expand popup menu with "add translation" option
- [x] add new form component for additional translation with submit and back options
- [x] submitting form stores the new translation in the overall words array
- [x] update edit logic to include an edit option for the new translation

**Comment by marvinRoellecke** [comment]
well done! 👏
