### ISSUE TITLE
connect database (US-18)

### ISSUE THREAD

**Issue by ufelgen** [ufelgen/capstone-project#35]
## Value Proposition

**As a** user  
**I want to** save my data in a database instead of the local storage  
**so that** i) I can access the same content from different devices/browsers, ii) my vocabulary is not lost upon local storage clearance
​

## Description

The app accesses one big array where all the data is stored. Currently, this array lives in a state in the local storage. The aim of this US is to fully replace the usage of local storage with the database connection. 
​

## Acceptance Criteria

- [x] app still works the same as before
- [x] newly added data is not lost upon deletion of items in local storage 
      ​

## Tasks

- [x] create api folder which hosts handler functions
- [x] create MongoDB and install mongoose
- [x] create db folder with dbconnect.js and .env files
- [x] create models sub-folder with Words.js which hosts schema
- [x] replace all local storage state (setter) calls with the corresponding CRUD operation
- [x] connect Atlas so that data lives on a remote server
- [x] equip Vercel with necessary info to connect to database 
      ​

## Complexity

😱

**Comment by Hirnstromwelle** [comment]
Hi Ulli, the user story fits for me as a user. He does not want to understand the background anyway. ^^ Maybe I would split them, but is a bit much at once. But that's up to you.

**Comment by ufelgen** [comment]
> Hi Ulli, the user story fits for me as a user. He does not want to understand the background anyway. ^^ Maybe I would split them, but is a bit much at once. But that's up to you.

Thank you Alex! Yes, I thought about splitting the user story but I couldn't come up with a way in which the app would still be functional. I guess I will leave it like this... good suggestion though, will probably be quite a big PR...
