### ISSUE TITLE
Checklist for QA Database Connection

### ISSUE THREAD

**Issue by ufelgen** [ufelgen/capstone-project#39]
Following [this US](https://github.com/ufelgen/capstone-project/issues/35) I replaced the local storage by a database connection. Therefore I had to change all the `create` and `update` functions, so they need to be quality tested again. 

As these are quite a lot of functions, I made a checklist of functions for QA.

### main page
<img width="334" alt="Bildschirmfoto 2023-01-13 um 12 33 46" src="https://user-images.githubusercontent.com/115288914/212311078-a7c8bd9a-ac18-4eca-b3b8-bb5d2292c281.png">

- [ ] add a new word (form at the top of the page) - you can put this in a new category so you can
- [ ] edit the category name (... button opens the popup menu, see image above) and
- [ ] delete this category

### category pages
<img width="331" alt="Bildschirmfoto 2023-01-13 um 12 36 29" src="https://user-images.githubusercontent.com/115288914/212311552-1b577c84-8be7-447a-9b5f-7dfd4e3201fa.png">

open the ... popup menu (see above) to
- [ ] edit the word
- [ ] add another translation
- [ ] edit the word again (now with two translations)
- [ ] add notes to a word
- [ ] edit those notes
- [ ] add a declension to a noun
- [ ] edit this declension 
- [ ] delete the word

### conjugations
conjugations are carried out automatically for a word in Slovenian upon providing some info in a form. to test this, you can
- [ ] add a new word "kupiti" - "to buy" to the "verbs" category via the form on the main page, then
- [ ] route to the "verbs" page, open the popup menu for the newly added "kupiti", select "+ conjugation" and write in the three form fields "kupi / kupil / kupila", and click "add"

the conjugation page should open automatically, where you can
- [ ] edit the present
- [ ] edit the past 
- [ ] edit the future

Thank you 🙏
