### ISSUE TITLE
Form to add new cards (US-4)

### ISSUE THREAD

**Issue by ufelgen** [ufelgen/capstone-project#4]
## Value Proposition

**As a** user

**I want to** add my own vocabulary

**to be able to** personalize my learning experience

## Description

![image](https://user-images.githubusercontent.com/115288914/207084449-949f4c02-4433-4cfe-bdc1-c5dd331a9d3a.png)

## Acceptance Criteria

- [x] a form is added on the main page (category overview) with the following elements
- [x] required text input field for the word in the base language (label: english flag)
- [x] required text input fields for the word in query language 1: the label is a dropdown menu for different languages (displaying flags) and (optional) where the last chosen language is pre-selected
- [x] an optional form field with a dropdown menu ( --empty--, m, f, n) where the user can specify gender if the word is a noun
- [x] required choose-one form field with a dropdown menu where the user can assign the word to a category (dropdown options: all existing categories)
- [x] a submit button that adds the form data to the correct category

## Tasks

- [x] work on a branch
- [x] add a form component as described above
- [x] the form data is appended to the correct category
- [ ] storybook/ testing

**Comment by flipkoehler** [comment]
ahhh! Now I understand what the dropdown magic should do 😄 
The story looks good, I have just two minor ideas: 
1) "a submit button that adds the form data to the correct category" > maybe this is more a task than an AC?!
2) Maybe you can add a placeholder text oder label for the input fields (e.g. word base language). That will make it easier to understand what I should write down 👍
