### ISSUE TITLE
Implement login (US-19)

### ISSUE THREAD

**Issue by ufelgen** [ufelgen/capstone-project#40]
## Value Proposition

**As a** user 
**I want to** be able to login in to the app  
**so that** eventually only I can see and edit my vocab cards, and another user will access only theirs (see next US)
​

## Description

![image](https://user-images.githubusercontent.com/115288914/212330154-f08812e5-1e37-4514-a649-c37956bc266a.png)
​

## Acceptance Criteria

- [x] new initial page has a "login" button
- [x] clicking this button routes to the `login with <authentication provider>` page provided by next-auth
- [x] successfully entering login details routes to the main page 
- [x] main page has a "logout" button
- [x] clicking this button ends the session and routes back to the login page
      ​

## Tasks

- [x] install next-auth
- [x] create pages/api/auth/[...nextauth].js with authentication provider GitHub
- [x] authorize access on GitHub and save in .env.local GitHub ID and secret
- [x] implement functionality for login and logout buttons
      ​
