### ISSUE TITLE
Connect database collection objects to logged-in user (US-20)

### ISSUE THREAD

**Issue by ufelgen** [ufelgen/capstone-project#41]
## Value Proposition

**As a** user 
**I want to** see and be able to edit only my vocab cards  
**so that** no one else can access my vocab cards and instead have their own collection
​

## Description

each object in the "words" collection of the "flashcards-extreme" database is connected to a user. this is achieved by adding a "user" key to all objects and adjusting the GET requests.
(this US builds on the [previous login US](https://github.com/ufelgen/capstone-project/issues/40)
​

## Acceptance Criteria

- [x] only the vocab cards that are connected to the logged-in user are shown
- [x] this means no vocab cards are shown when a new user logs in
      ​

## Tasks

- [x] a user-userID key-value pair is added to each object in the database collection 
- [x] this happens on server side with the session object's info
- [x] update GET requests to render only the logged-in user's vocab cards
      ​

## Complexity

🤯
