### ISSUE TITLE
Delete declension/conjugation/notes (US-21)

### ISSUE THREAD

**Issue by ufelgen** [ufelgen/capstone-project#45]
## Value Proposition

**As a** user  
**I want to** be able to delete saved declensions, conjugations and notes from a vocab card  
**so that** I can start over if I made a mistake
​

## Description

![image](https://user-images.githubusercontent.com/115288914/212641961-62cb9b70-2045-4048-94c2-274211be6f7e.png)

## Acceptance Criteria

- [x] dynamic declension, conjugation and notes pages get a "delete" button
- [x] clicking this button opens a window to ask if the user would like to delete this declension/conjugation/notes info
- [x] confirming deletes the respective declension, conjugation or notes and
- [x] routes back to the category overview page
      ​

## Tasks

- [x] add a button to dynamic declension, conjugation and notes pages
- [x] implement logic to update the respective word object via PUT

**Comment by Hirnstromwelle** [comment]
i like it. let's go : )
