### ISSUE TITLE
add login provider (US-xx)

### ISSUE THREAD

**Issue by ufelgen** [ufelgen/capstone-project#48]
## Value Proposition

**As a** user  
**I want to** be able to sign into the app through different next-auth providers  
**so that** I can use the app even if I don't have a GitHub account
​

## Description

log-in page provided by next-auth gives more log-in options than just GitHub
​

## Acceptance Criteria

- [ ] it's possible to sign into flashcards extreme with google
- [ ] optional: it's possible to sign into flashcards extreme with facebook
      ​

## Tasks

- [ ] update [...nextauth].js to include more providers
- [ ] figure out where the ids and secrets come from 
      ​

**Comment by AntjeWalter** [comment]
Nice feature!
