### ISSUE TITLE
Specify own categories (US-5)

### ISSUE THREAD

**Issue by ufelgen** [ufelgen/capstone-project#5]
## Value Proposition

**As a** user,
**I want to** be able to create my own vocab categories when adding a new word,
**in order to** improve the structure of my learning experience
​

## Description

![image](https://user-images.githubusercontent.com/115288914/207085632-b9d425a2-184a-43f3-97ed-f4deddf461f4.png)
​

## Acceptance Criteria

- [ ] the category dropdown element of the form has an additional option "add new category"
- [ ] selecting this category changes the dropdown element to an input element where the user can type their new category
- [x] a new category cannot be created independently (only in association with a new word pair) and is added through the "add word" submit button that the form uses
- [x] upon specifying a new category name with a word pair, this new category is rendered on the category overview page 
      ​

## Tasks

- [x] work on a branch
- [x] extend the category dropdown element by another option
- [ ] conditionally render the input element for entering a new category
- [x] form functionality: store the newly generated data as an object in the dummy data array
- [x] render a new category on the category overview page 
- [ ] storybook/testing
      ​

**Comment by marvinRoellecke** [comment]
excellent user story. 👏

How do you submit the new category after you typed in the new name?
Do you click on a submit button, press enter or does it automatically save when click somewhere outside the input field

**Comment by ufelgen** [comment]
> excellent user story. 👏
> 
> How do you submit the new category after you typed in the new name? Do you click on a submit button, press enter or does it automatically save when click somewhere outside the input field

Thank you, Marvin! very good remarks, I will phrase it differently to (hopefully) make it clearer
